name: Terraform Validate and Fmt

on:
  pull_request:
    paths:
      - '**/*.tf'
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.10.4"

      - name: Terraform Init
        run: terraform init || { echo 'Terraform init failed' ; exit 1; }

      - name: Run terraform fmt
        run: terraform fmt -check -recursive

      - name: Run terraform validate
        run: terraform validate
